blank_issues_enabled: true
contact_links:
  - name: Yukki Support
    url: https://t.me/Urap_Bot
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://rMahdi.ir/
    about: Documentation for getting started with bot.
